/**:
    ros__parameters:
      registration_method: "NDT"
      ndt_resolution: 2.0
      ndt_step_size: 0.1
      transform_epsilon: 0.01
      voxel_leaf_size: 0.05
      scan_max_range: 100.0
      scan_min_range: 0.5
      scan_period: 0.1
      use_pcd_map: true
      map_path: /workspaces/isaac_ros-dev/src/pcl_localization_ros2/data/map_mfi_post_processed.pcd
      set_initial_pose: true
      initial_pose_x: 2.0
      initial_pose_y: 1.0
      initial_pose_z: 0.
      initial_pose_qx: 0.0
      initial_pose_qy: 0.0
      initial_pose_qz: 0.0
      initial_pose_qw: 1.0
      use_odom: true
      use_imu: false
      enable_debug: false
